# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-03-26 10:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MoodPlayer', '0002_auto_20180317_1103'),
    ]

    operations = [
        migrations.CreateModel(
            name='song_metadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MoodPlayer.user_preference')),
            ],
        ),
    ]
