# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-03-27 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoodPlayer', '0003_song_metadata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song_metadata',
            name='user_id',
        ),
        migrations.AddField(
            model_name='song_metadata',
            name='genre',
            field=models.CharField(default='pop', max_length=5),
        ),
        migrations.AddField(
            model_name='song_metadata',
            name='mood',
            field=models.CharField(default='happy', max_length=10),
        ),
        migrations.AddField(
            model_name='song_metadata',
            name='path',
            field=models.CharField(default='/Users/WolfDen/Desktop/songs/', max_length=100),
        ),
        migrations.AddField(
            model_name='song_metadata',
            name='size',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='song_metadata',
            name='song_id',
            field=models.CharField(default='song_100', max_length=15),
        ),
        migrations.AddField(
            model_name='song_metadata',
            name='song_length',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='song_metadata',
            name='title',
            field=models.CharField(default='abc', max_length=100),
        ),
    ]
