# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-03-26 14:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MoodPlayer', '0003_auto_20180326_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like_song',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
