# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-03-26 15:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MoodPlayer', '0006_auto_20180326_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_preference',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='MoodPlayer.usermodel'),
        ),
    ]
