# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-03-28 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoodPlayer', '0007_auto_20180326_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='song_metadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_id', models.CharField(default='song_100', max_length=15)),
                ('title', models.CharField(default='abc', max_length=100)),
                ('song_length', models.IntegerField(default=0)),
                ('size', models.IntegerField(default=0)),
                ('path', models.CharField(default='/Users/WolfDen/Desktop/songs/', max_length=100)),
                ('genre', models.CharField(default='pop', max_length=5)),
                ('mood', models.CharField(default='happy', max_length=10)),
            ],
        ),
    ]
