# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-03-29 00:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MoodPlayer', '0008_song_metadata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_preference',
            old_name='jazz',
            new_name='rap',
        ),
    ]
