# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-03-29 00:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MoodPlayer', '0009_auto_20180329_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hate_song',
            name='song_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MoodPlayer.song_metadata'),
        ),
        migrations.AlterField(
            model_name='like_song',
            name='song_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MoodPlayer.song_metadata'),
        ),
    ]
