# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-03-31 19:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MoodPlayer', '0004_auto_20180327_2058'),
        ('MoodPlayer', '0010_auto_20180329_0137'),
    ]

    operations = [
    ]
